# Generated by Django 3.0.7 on 2020-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Ширина')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('average_check', models.FloatField(verbose_name='Средний чек')),
                ('id_2gis', models.CharField(max_length=40, verbose_name='ID 2GIS')),
            ],
        ),
    ]
