# Generated by Django 3.0.7 on 2020-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201024_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id_2gis',
            field=models.CharField(max_length=300, verbose_name='ID 2GIS'),
        ),
    ]
